export const MOROCCO_LOCATIONS: { name: string; city: string; type: 'hotel' | 'riad' | 'airport' | 'landmark' | 'medina' }[] = [
  // ─── CASABLANCA ─────────────────────────────────────────────────────────────
  { name: 'Hyatt Regency Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Four Seasons Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Sofitel Casablanca Tour Blanche', city: 'Casablanca', type: 'hotel' },
  { name: 'Le Casablanca Hotel', city: 'Casablanca', type: 'hotel' },
  { name: 'Kenzi Tower Hotel', city: 'Casablanca', type: 'hotel' },
  { name: 'Barceló Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Sheraton Casablanca Hotel', city: 'Casablanca', type: 'hotel' },
  { name: 'Mövenpick Hotel Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Novotel Casablanca City Center', city: 'Casablanca', type: 'hotel' },
  { name: 'Hotel & Spa Le Doge', city: 'Casablanca', type: 'hotel' },
  { name: 'Ibis Casablanca City Center', city: 'Casablanca', type: 'hotel' },
  { name: 'Golden Tulip Farah Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Atlas Almohades Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Kenzi Basma Hotel', city: 'Casablanca', type: 'hotel' },
  { name: 'Imperial Casablanca Hotel', city: 'Casablanca', type: 'hotel' },
  { name: 'Pestana Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Mogador Marina', city: 'Casablanca', type: 'hotel' },
  { name: 'Idou Anfa Hotel', city: 'Casablanca', type: 'hotel' },
  { name: 'Hotel Transatlantique Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Melliber Appart Hotel', city: 'Casablanca', type: 'hotel' },
  { name: 'Onomo Hotel Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Moroccan House Hotel', city: 'Casablanca', type: 'hotel' },
  { name: 'Hotel Suisse Casablanca', city: 'Casablanca', type: 'hotel' },
  { name: 'Best Western Hotel Toubkal', city: 'Casablanca', type: 'hotel' },
  { name: 'Hassan II Mosque', city: 'Casablanca', type: 'landmark' },
  { name: 'Morocco Mall', city: 'Casablanca', type: 'landmark' },
  { name: 'Gare Casa Voyageurs', city: 'Casablanca', type: 'landmark' },
  { name: 'Marina Casablanca', city: 'Casablanca', type: 'landmark' },
  { name: 'Casablanca Medina', city: 'Casablanca', type: 'medina' },
  { name: 'Ain Diab Beach', city: 'Casablanca', type: 'landmark' },
  { name: 'Anfa Place', city: 'Casablanca', type: 'landmark' },

  // ─── MARRAKECH ──────────────────────────────────────────────────────────────
  { name: 'Mamounia Hotel', city: 'Marrakech', type: 'hotel' },
  { name: 'Royal Mansour Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Four Seasons Resort Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Sofitel Marrakech Palais Imperial', city: 'Marrakech', type: 'hotel' },
  { name: 'Movenpick Hotel Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Mandarin Oriental Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Fairmont Royal Palm Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Selman Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Oberoi Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Es Saadi Marrakech Resort', city: 'Marrakech', type: 'hotel' },
  { name: 'Kenzi Menara Palace', city: 'Marrakech', type: 'hotel' },
  { name: 'Kenzi Club Agdal Medina', city: 'Marrakech', type: 'hotel' },
  { name: 'Savoy Le Grand Hotel Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Novotel Marrakech Hivernage', city: 'Marrakech', type: 'hotel' },
  { name: 'Ibis Marrakech Centre Gare', city: 'Marrakech', type: 'hotel' },
  { name: 'Radisson Blu Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Mogador Kasbah Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Palm Plaza Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Atlas Medina & Spa Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Aqua Mirage Club Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Barceló Palmeraie Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Pullman Marrakech Palmeraie', city: 'Marrakech', type: 'hotel' },
  { name: 'Hotel & Ryads Barriere Le Naoura', city: 'Marrakech', type: 'hotel' },
  { name: 'Riu Tikida Garden Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Labranda Rose Aqua Parc', city: 'Marrakech', type: 'hotel' },
  { name: 'Opera Plaza Hotel Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Le Méridien N'Fis Marrakech', city: 'Marrakech', type: 'hotel' },
  { name: 'Vizir Center Parc & Aqua', city: 'Marrakech', type: 'hotel' },
  { name: 'Riad Yasmine', city: 'Marrakech', type: 'riad' },
  { name: 'Riad BE Marrakech', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Kniza', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Jardin Secret', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Dar Anika', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Joya Marrakech', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Les Yeux Bleus', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Lotus Perle', city: 'Marrakech', type: 'riad' },
  { name: 'Riad El Fenn', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Farnatchi', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Star Marrakech', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Kheirredine', city: 'Marrakech', type: 'riad' },
  { name: 'Riad 72 Marrakech', city: 'Marrakech', type: 'riad' },
  { name: 'Riad Dar Darma', city: 'Marrakech', type: 'riad' },
  { name: 'Jemaa el-Fna Square', city: 'Marrakech', type: 'landmark' },
  { name: 'Majorelle Garden', city: 'Marrakech', type: 'landmark' },
  { name: 'Marrakech Medina', city: 'Marrakech', type: 'medina' },
  { name: 'Gueliz District', city: 'Marrakech', type: 'landmark' },
  { name: 'Hivernage District', city: 'Marrakech', type: 'landmark' },
  { name: 'Palmeraie Marrakech', city: 'Marrakech', type: 'landmark' },
  { name: 'Koutoubia Mosque', city: 'Marrakech', type: 'landmark' },
  { name: 'Bahia Palace', city: 'Marrakech', type: 'landmark' },
  { name: 'Saadian Tombs', city: 'Marrakech', type: 'landmark' },
  { name: 'Menara Gardens', city: 'Marrakech', type: 'landmark' },

  // ─── RABAT ──────────────────────────────────────────────────────────────────
  { name: 'Sofitel Rabat Jardin des Roses', city: 'Rabat', type: 'hotel' },
  { name: 'Hyatt Regency Rabat', city: 'Rabat', type: 'hotel' },
  { name: 'Hotel Balima Rabat', city: 'Rabat', type: 'hotel' },
  { name: 'The View Hotel Rabat', city: 'Rabat', type: 'hotel' },
  { name: 'Farah Rabat Hotel', city: 'Rabat', type: 'hotel' },
  { name: 'Le Diwan Rabat', city: 'Rabat', type: 'hotel' },
  { name: 'Hotel Tour Hassan Palace', city: 'Rabat', type: 'hotel' },
  { name: 'Cantor Hotel Rabat', city: 'Rabat', type: 'hotel' },
  { name: 'Ibis Rabat Agdal', city: 'Rabat', type: 'hotel' },
  { name: 'Novotel Rabat', city: 'Rabat', type: 'hotel' },
  { name: 'Golden Tulip Farah Rabat', city: 'Rabat', type: 'hotel' },
  { name: 'Mercure Rabat Sheherazade', city: 'Rabat', type: 'hotel' },
  { name: 'Riad Kalaa Rabat', city: 'Rabat', type: 'riad' },
  { name: 'Riad Dar El Kebira Rabat', city: 'Rabat', type: 'riad' },
  { name: 'Hassan Tower', city: 'Rabat', type: 'landmark' },
  { name: 'Rabat Medina', city: 'Rabat', type: 'medina' },
  { name: 'Kasbah of the Udayas', city: 'Rabat', type: 'landmark' },
  { name: 'Gare Rabat Ville', city: 'Rabat', type: 'landmark' },
  { name: 'Chellah Ruins', city: 'Rabat', type: 'landmark' },
  { name: 'Royal Palace Rabat', city: 'Rabat', type: 'landmark' },

  // ─── FEZ ────────────────────────────────────────────────────────────────────
  { name: 'Palais Faraj Suites & Spa', city: 'Fez', type: 'hotel' },
  { name: 'Sofitel Fes Palais Jamaï', city: 'Fez', type: 'hotel' },
  { name: 'Hotel Sahrai Fez', city: 'Fez', type: 'hotel' },
  { name: 'Marriott Jnan Palace Fes', city: 'Fez', type: 'hotel' },
  { name: 'Barceló Fes Medina', city: 'Fez', type: 'hotel' },
  { name: 'Ibis Fes', city: 'Fez', type: 'hotel' },
  { name: 'Zalagh Kasbah Hotel Fez', city: 'Fez', type: 'hotel' },
  { name: 'Atlas Fes Hotel', city: 'Fez', type: 'hotel' },
  { name: 'Menzeh Zalagh Hotel', city: 'Fez', type: 'hotel' },
  { name: 'Hotel Volubilis Fes', city: 'Fez', type: 'hotel' },
  { name: 'Riad Fes', city: 'Fez', type: 'riad' },
  { name: 'Riad Laaroussa', city: 'Fez', type: 'riad' },
  { name: 'Riad Myra Fez', city: 'Fez', type: 'riad' },
  { name: 'Riad Maison Bleue Fez', city: 'Fez', type: 'riad' },
  { name: 'Riad Hala Fez', city: 'Fez', type: 'riad' },
  { name: 'Riad Anata Fez', city: 'Fez', type: 'riad' },
  { name: 'Riad Idrissy Fez', city: 'Fez', type: 'riad' },
  { name: 'Riad Alkantara Fez', city: 'Fez', type: 'riad' },
  { name: 'Karawan Riad Fez', city: 'Fez', type: 'riad' },
  { name: 'Fez el-Bali Medina', city: 'Fez', type: 'medina' },
  { name: 'Fez el-Jadid', city: 'Fez', type: 'landmark' },
  { name: 'Bab Bou Jeloud', city: 'Fez', type: 'landmark' },
  { name: 'Chouara Tannery', city: 'Fez', type: 'landmark' },
  { name: 'Al-Attarine Madrasa', city: 'Fez', type: 'landmark' },
  { name: 'Bou Inania Madrasa', city: 'Fez', type: 'landmark' },
  { name: 'Mellah Fez', city: 'Fez', type: 'landmark' },

  // ─── TANGIER ────────────────────────────────────────────────────────────────
  { name: 'Hilton Tangier Al Houara Resort', city: 'Tangier', type: 'hotel' },
  { name: 'El Minzah Hotel', city: 'Tangier', type: 'hotel' },
  { name: 'Mövenpick Hotel Tangier', city: 'Tangier', type: 'hotel' },
  { name: 'Hilton Garden Inn Tangier', city: 'Tangier', type: 'hotel' },
  { name: 'Kenzi Solazur Hotel Tangier', city: 'Tangier', type: 'hotel' },
  { name: 'Farah Tanger Hotel', city: 'Tangier', type: 'hotel' },
  { name: 'Ibis Tanger City Center', city: 'Tangier', type: 'hotel' },
  { name: 'Hotel Continental Tangier', city: 'Tangier', type: 'hotel' },
  { name: 'Barceló Tanger', city: 'Tangier', type: 'hotel' },
  { name: 'Hotel Rif & Spa Tangier', city: 'Tangier', type: 'hotel' },
  { name: 'Royal Tulip City Center Tangier', city: 'Tangier', type: 'hotel' },
  { name: 'Marina Bay Hotel Tangier', city: 'Tangier', type: 'hotel' },
  { name: 'Riad Nord-Pinus Tangier', city: 'Tangier', type: 'riad' },
  { name: 'Riad Dar Nour Tangier', city: 'Tangier', type: 'riad' },
  { name: 'Tangier Medina', city: 'Tangier', type: 'medina' },
  { name: 'Tangier Port', city: 'Tangier', type: 'landmark' },
  { name: 'Cape Spartel', city: 'Tangier', type: 'landmark' },
  { name: 'Hercules Caves', city: 'Tangier', type: 'landmark' },
  { name: 'Grand Socco Tangier', city: 'Tangier', type: 'landmark' },
  { name: 'Tanger Med Port', city: 'Tangier', type: 'landmark' },

  // ─── AGADIR ─────────────────────────────────────────────────────────────────
  { name: 'Sofitel Agadir Royal Bay Resort', city: 'Agadir', type: 'hotel' },
  { name: 'RIU Tikida Beach Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Iberostar Founty Beach', city: 'Agadir', type: 'hotel' },
  { name: 'Atlantic Palace Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Robinson Club Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Hotel Argana Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Kenzi Europa Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Anezi Tower Hotel Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Royal Atlas Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Tikida Golf Palace Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Paradis Plage Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Hyatt Place Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Labranda Les Dunes d\'Or Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'LTI Agadir Beach Club', city: 'Agadir', type: 'hotel' },
  { name: 'Hotel Timoulay & Spa Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Allegro Agadir', city: 'Agadir', type: 'hotel' },
  { name: 'Agadir Beach', city: 'Agadir', type: 'landmark' },
  { name: 'Agadir Oufella Ruins', city: 'Agadir', type: 'landmark' },
  { name: 'Souk El Had Agadir', city: 'Agadir', type: 'landmark' },
  { name: 'Marina Agadir', city: 'Agadir', type: 'landmark' },
  { name: 'Crocoparc Agadir', city: 'Agadir', type: 'landmark' },

  // ─── MEKNES ─────────────────────────────────────────────────────────────────
  { name: 'Hotel Transatlantique Meknes', city: 'Meknes', type: 'hotel' },
  { name: 'Ibis Meknes', city: 'Meknes', type: 'hotel' },
  { name: 'Hotel Zaki Meknes', city: 'Meknes', type: 'hotel' },
  { name: 'Riad Yacout Meknes', city: 'Meknes', type: 'riad' },
  { name: 'Riad D\'Or Meknes', city: 'Meknes', type: 'riad' },
  { name: 'Riad Lahboul Meknes', city: 'Meknes', type: 'riad' },
  { name: 'Palais Didi Meknes', city: 'Meknes', type: 'hotel' },
  { name: 'Bab Mansour Gate', city: 'Meknes', type: 'landmark' },
  { name: 'Meknes Medina', city: 'Meknes', type: 'medina' },
  { name: 'Royal Stables Meknes', city: 'Meknes', type: 'landmark' },
  { name: 'Volubilis Ruins', city: 'Meknes', type: 'landmark' },
  { name: 'Moulay Ismail Mausoleum', city: 'Meknes', type: 'landmark' },

  // ─── CHEFCHAOUEN ────────────────────────────────────────────────────────────
  { name: 'Lina Ryad & Spa Chefchaouen', city: 'Chefchaouen', type: 'hotel' },
  { name: 'Casa Hassan Chefchaouen', city: 'Chefchaouen', type: 'hotel' },
  { name: 'Hotel Parador Chefchaouen', city: 'Chefchaouen', type: 'hotel' },
  { name: 'Dar Echchaouen', city: 'Chefchaouen', type: 'hotel' },
  { name: 'Hotel Atlas Chefchaouen', city: 'Chefchaouen', type: 'hotel' },
  { name: 'Riad Cherifa', city: 'Chefchaouen', type: 'riad' },
  { name: 'Riad Hicham Chefchaouen', city: 'Chefchaouen', type: 'riad' },
  { name: 'Riad Assilah Chefchaouen', city: 'Chefchaouen', type: 'riad' },
  { name: 'Dar Meziana Chefchaouen', city: 'Chefchaouen', type: 'riad' },
  { name: 'Riad Baraka Chefchaouen', city: 'Chefchaouen', type: 'riad' },
  { name: 'Chefchaouen Blue Medina', city: 'Chefchaouen', type: 'medina' },
  { name: 'Place Uta el-Hammam', city: 'Chefchaouen', type: 'landmark' },
  { name: 'Ras el-Maa Waterfall', city: 'Chefchaouen', type: 'landmark' },
  { name: 'Spanish Mosque Chefchaouen', city: 'Chefchaouen', type: 'landmark' },

  // ─── ESSAOUIRA ──────────────────────────────────────────────────────────────
  { name: 'Sofitel Essaouira Mogador Golf & Spa', city: 'Essaouira', type: 'hotel' },
  { name: 'Heure Bleue Palais Essaouira', city: 'Essaouira', type: 'hotel' },
  { name: 'Hotel Atlas Essaouira', city: 'Essaouira', type: 'hotel' },
  { name: 'Mogador Essaouira', city: 'Essaouira', type: 'hotel' },
  { name: 'Villa Maroc Essaouira', city: 'Essaouira', type: 'hotel' },
  { name: 'Dar L\'Oussia Essaouira', city: 'Essaouira', type: 'hotel' },
  { name: 'Le Medina Essaouira Hotel Thalassa', city: 'Essaouira', type: 'hotel' },
  { name: 'Riad Mimouna Essaouira', city: 'Essaouira', type: 'riad' },
  { name: 'Riad Baladin Essaouira', city: 'Essaouira', type: 'riad' },
  { name: 'Riad Al Madina Essaouira', city: 'Essaouira', type: 'riad' },
  { name: 'Riad Chbanate Essaouira', city: 'Essaouira', type: 'riad' },
  { name: 'Essaouira Medina', city: 'Essaouira', type: 'medina' },
  { name: 'Essaouira Beach', city: 'Essaouira', type: 'landmark' },
  { name: 'Skala de la Ville', city: 'Essaouira', type: 'landmark' },
  { name: 'Port of Essaouira', city: 'Essaouira', type: 'landmark' },

  // ─── OUARZAZATE ─────────────────────────────────────────────────────────────
  { name: 'Berbère Palace Ouarzazate', city: 'Ouarzazate', type: 'hotel' },
  { name: 'Le Riad Salam Ouarzazate', city: 'Ouarzazate', type: 'hotel' },
  { name: 'Kenzi Azghor Hotel Ouarzazate', city: 'Ouarzazate', type: 'hotel' },
  { name: 'Hotel Oscar Ouarzazate', city: 'Ouarzazate', type: 'hotel' },
  { name: 'Ksar Ighnda Ouarzazate', city: 'Ouarzazate', type: 'hotel' },
  { name: 'Le Temple des Arts Ouarzazate', city: 'Ouarzazate', type: 'hotel' },
  { name: 'Riad Dar Chamaa Ouarzazate', city: 'Ouarzazate', type: 'riad' },
  { name: 'Atlas Corporation Studios', city: 'Ouarzazate', type: 'landmark' },
  { name: 'Kasbah Taourirt', city: 'Ouarzazate', type: 'landmark' },
  { name: 'Aït Benhaddou Kasbah', city: 'Ouarzazate', type: 'landmark' },
  { name: 'Fint Oasis Ouarzazate', city: 'Ouarzazate', type: 'landmark' },

  // ─── MERZOUGA / SAHARA ──────────────────────────────────────────────────────
  { name: 'Kasbah Tombouctou Merzouga', city: 'Merzouga', type: 'hotel' },
  { name: 'Desert Luxury Camp Erg Chebbi', city: 'Merzouga', type: 'hotel' },
  { name: 'Riad Madu Merzouga', city: 'Merzouga', type: 'hotel' },
  { name: 'Kasbah Mohayut Merzouga', city: 'Merzouga', type: 'hotel' },
  { name: 'Auberge du Sud Merzouga', city: 'Merzouga', type: 'hotel' },
  { name: 'Kasbah Hotel Xaluca Merzouga', city: 'Merzouga', type: 'hotel' },
  { name: 'Erg Chebbi Luxury Camp', city: 'Merzouga', type: 'hotel' },
  { name: 'Sahara Stars Camp Merzouga', city: 'Merzouga', type: 'hotel' },
  { name: 'Erg Chebbi Dunes', city: 'Merzouga', type: 'landmark' },
  { name: 'Merzouga Village', city: 'Merzouga', type: 'landmark' },

  // ─── TAGHAZOUT ──────────────────────────────────────────────────────────────
  { name: 'Paradis Plage Surf Resort', city: 'Taghazout', type: 'hotel' },
  { name: 'Hyatt Place Taghazout Bay', city: 'Taghazout', type: 'hotel' },
  { name: 'Fairmont Taghazout Bay', city: 'Taghazout', type: 'hotel' },
  { name: 'Radisson Blu Resort Taghazout', city: 'Taghazout', type: 'hotel' },
  { name: 'Sol House Taghazout Bay', city: 'Taghazout', type: 'hotel' },
  { name: 'Tikida Golf Palace Taghazout', city: 'Taghazout', type: 'hotel' },
  { name: 'Taghazout Bay', city: 'Taghazout', type: 'landmark' },
  { name: 'Hash Point Beach', city: 'Taghazout', type: 'landmark' },
  { name: 'Banana Village', city: 'Taghazout', type: 'landmark' },

  // ─── EL JADIDA ──────────────────────────────────────────────────────────────
  { name: 'Mazagan Beach & Golf Resort', city: 'El Jadida', type: 'hotel' },
  { name: 'Pullman El Jadida Royal Golf', city: 'El Jadida', type: 'hotel' },
  { name: 'Hotel Ibis El Jadida', city: 'El Jadida', type: 'hotel' },
  { name: 'Hotel L\'Iglesia El Jadida', city: 'El Jadida', type: 'hotel' },
  { name: 'Riad Soleil d\'Or El Jadida', city: 'El Jadida', type: 'riad' },
  { name: 'Portuguese Cistern El Jadida', city: 'El Jadida', type: 'landmark' },
  { name: 'El Jadida Medina', city: 'El Jadida', type: 'medina' },
  { name: 'El Jadida Beach', city: 'El Jadida', type: 'landmark' },

  // ─── MOHAMMEDIA ─────────────────────────────────────────────────────────────
  { name: 'Hotel Samir Mohammedia', city: 'Mohammedia', type: 'hotel' },
  { name: 'Novotel Mohammedia', city: 'Mohammedia', type: 'hotel' },
  { name: 'Avanti Hotel Mohammedia', city: 'Mohammedia', type: 'hotel' },
  { name: 'Hotel Sabah Mohammedia', city: 'Mohammedia', type: 'hotel' },
  { name: 'Mohammedia Beach', city: 'Mohammedia', type: 'landmark' },
  { name: 'Mohammedia Port', city: 'Mohammedia', type: 'landmark' },

  // ─── TETOUAN ────────────────────────────────────────────────────────────────
  { name: 'Hotel Blanco Riad Tetouan', city: 'Tetouan', type: 'hotel' },
  { name: 'Riad El Reducto Tetouan', city: 'Tetouan', type: 'riad' },
  { name: 'Hotel Marina Smir Tetouan', city: 'Tetouan', type: 'hotel' },
  { name: 'Sofitel Tamuda Bay Tetouan', city: 'Tetouan', type: 'hotel' },
  { name: 'Banyan Tree Tamouda Bay', city: 'Tetouan', type: 'hotel' },
  { name: 'Hotel Barceló Cabo Negro', city: 'Tetouan', type: 'hotel' },
  { name: 'Tetouan Medina', city: 'Tetouan', type: 'medina' },
  { name: 'Royal Palace Tetouan', city: 'Tetouan', type: 'landmark' },

  // ─── OUJDA ──────────────────────────────────────────────────────────────────
  { name: 'Atlas Orient Hotel Oujda', city: 'Oujda', type: 'hotel' },
  { name: 'Ibis Oujda', city: 'Oujda', type: 'hotel' },
  { name: 'Hotel Al Manar Oujda', city: 'Oujda', type: 'hotel' },
  { name: 'Hotel Royal Oujda', city: 'Oujda', type: 'hotel' },
  { name: 'Oujda Medina', city: 'Oujda', type: 'medina' },
  { name: 'Sidi Yahia Oasis', city: 'Oujda', type: 'landmark' },

  // ─── DAKHLA ─────────────────────────────────────────────────────────────────
  { name: 'Dakhla Attitude Hotel', city: 'Dakhla', type: 'hotel' },
  { name: 'Dakhla Club Hotel', city: 'Dakhla', type: 'hotel' },
  { name: 'Westpoint Dakhla', city: 'Dakhla', type: 'hotel' },
  { name: 'PK25 Dakhla', city: 'Dakhla', type: 'hotel' },
  { name: 'Hotel Sahara Regency Dakhla', city: 'Dakhla', type: 'hotel' },
  { name: 'Dakhla Lagoon', city: 'Dakhla', type: 'landmark' },
  { name: 'White Dune Dakhla', city: 'Dakhla', type: 'landmark' },

  // ─── LAÂYOUNE ───────────────────────────────────────────────────────────────
  { name: 'Hotel Parador Laâyoune', city: 'Laâyoune', type: 'hotel' },
  { name: 'Hotel Sahara Line Laâyoune', city: 'Laâyoune', type: 'hotel' },
  { name: 'Hotel Nagjir Laâyoune', city: 'Laâyoune', type: 'hotel' },

  // ─── IFRANE ─────────────────────────────────────────────────────────────────
  { name: 'Michlifen Ifrane Suites & Spa', city: 'Ifrane', type: 'hotel' },
  { name: 'Hotel Perce-Neige Ifrane', city: 'Ifrane', type: 'hotel' },
  { name: 'Hôtel des Cèdres Ifrane', city: 'Ifrane', type: 'hotel' },
  { name: 'Al Akhawayn University', city: 'Ifrane', type: 'landmark' },
  { name: 'Ifrane National Park', city: 'Ifrane', type: 'landmark' },

  // ─── BENI MELLAL ────────────────────────────────────────────────────────────
  { name: 'Hotel Ouzoud Beni Mellal', city: 'Beni Mellal', type: 'hotel' },
  { name: 'Widiane Suite & Spa', city: 'Beni Mellal', type: 'hotel' },
  { name: 'Ouzoud Waterfalls', city: 'Beni Mellal', type: 'landmark' },

  // ─── ERRACHIDIA ─────────────────────────────────────────────────────────────
  { name: 'Hotel Kenzi Rissani Errachidia', city: 'Errachidia', type: 'hotel' },
  { name: 'Kasbah Hotel Xaluca Errachidia', city: 'Errachidia', type: 'hotel' },
  { name: 'Ziz Valley Gorges', city: 'Errachidia', type: 'landmark' },

  // ─── TINGHIR / TODRA ────────────────────────────────────────────────────────
  { name: 'Hotel Tomboctou Tinghir', city: 'Tinghir', type: 'hotel' },
  { name: 'Riad Dar Bab Todra', city: 'Tinghir', type: 'riad' },
  { name: 'Kasbah Lamrani Tinghir', city: 'Tinghir', type: 'hotel' },
  { name: 'Todra Gorges', city: 'Tinghir', type: 'landmark' },

  // ─── MIDELT ─────────────────────────────────────────────────────────────────
  { name: 'Hotel Kasbah Asmaa Midelt', city: 'Midelt', type: 'hotel' },
  { name: 'Hotel Taddart Midelt', city: 'Midelt', type: 'hotel' },

  // ─── ASILAH ─────────────────────────────────────────────────────────────────
  { name: 'Hotel Al Alba Asilah', city: 'Asilah', type: 'hotel' },
  { name: 'Dar Manara Asilah', city: 'Asilah', type: 'riad' },
  { name: 'Berbari Hotel Asilah', city: 'Asilah', type: 'hotel' },
  { name: 'Asilah Medina', city: 'Asilah', type: 'medina' },
  { name: 'Asilah Beach', city: 'Asilah', type: 'landmark' },

  // ─── SAIDIA ─────────────────────────────────────────────────────────────────
  { name: 'Barceló Mediterranean Saidia', city: 'Saidia', type: 'hotel' },
  { name: 'Be Live Collection Saidia', city: 'Saidia', type: 'hotel' },
  { name: 'Iberostar Saidia', city: 'Saidia', type: 'hotel' },
  { name: 'Saidia Beach', city: 'Saidia', type: 'landmark' },

  // ─── AL HOCEIMA ─────────────────────────────────────────────────────────────
  { name: 'Hotel Mohamed V Al Hoceima', city: 'Al Hoceima', type: 'hotel' },
  { name: 'Mercure Quemado Resort', city: 'Al Hoceima', type: 'hotel' },
  { name: 'Hotel Suites Alandis Al Hoceima', city: 'Al Hoceima', type: 'hotel' },
  { name: 'Quemado Beach', city: 'Al Hoceima', type: 'landmark' },

  // ─── NADOR ──────────────────────────────────────────────────────────────────
  { name: 'Hotel Rif Al Hoceima Nador', city: 'Nador', type: 'hotel' },
  { name: 'Hotel Mercure Rif Nador', city: 'Nador', type: 'hotel' },
  { name: 'Marchica Lagoon', city: 'Nador', type: 'landmark' },

  // ─── IMLIL / ATLAS ──────────────────────────────────────────────────────────
  { name: 'Kasbah du Toubkal', city: 'Imlil', type: 'hotel' },
  { name: 'Kasbah Tamadot', city: 'Imlil', type: 'hotel' },
  { name: 'Riad Atlas Toubkal', city: 'Imlil', type: 'riad' },
  { name: 'Douar Samra Imlil', city: 'Imlil', type: 'hotel' },
  { name: 'Mount Toubkal', city: 'Imlil', type: 'landmark' },
];
